// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddvzchwqrvdyexoewbxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkdnpjaHdxcnZkeWV4b2V3Ynh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjkzNDcsImV4cCI6MjA2NTU0NTM0N30.V-BH05Aw5ihoSrWzJMvKK7RfaQ1_m3fL68hCLcPXf58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);